#!/usr/bin/env bash
# Summary: List all Java versions available to jsenv
# Usage: jsenv versions [--bare]
#
# Lists all Java versions found in `$JSENV_ROOT/versions/*'.

set -e
[ -n "$JSENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  inst_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  inst_prefix="+ "
  miss_prefix="  "
  current_version="$(jenv-version-name || true)"
  include_system="1"
fi

echo "${current_version}"

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}${inst_prefix}$(jenv-version 2>/dev/null)"
  elif [[ -d  "${JENV_ROOT}/versions/$1" ]]; then
    echo "${miss_prefix}${inst_prefix}$1"
  else
    echo "${miss_prefix}${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && JENV_VERSION=system jenv-which java >/dev/null 2>&1; then
  print_version system
fi

for path in "${JENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done

for path in /Library/Java/JavaVirtualMachines/*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done

##################################
#for path in /System/Library/Java/JavaVirtualMachines/*; do
#  if [ -d "$path" ]; then
#    print_version "${path##*/}"
#  fi
#done
##################################
