#!/usr/bin/env bash
# Summary: Show the current Java provider

set -e
[ -n "$JENV_DEBUG" ] && set -x


JENV_VERSION="$(jenv-version-name)"
JENV_NUMBER=""

IFS=- read PROVIDER NUMBER <<< "$JENV_VERSION"

if [ -d "${JENV_ROOT}/versions/${PROVIDER}-${NUMBER}" ]; then
 JENV_NUMBER="${NUMBER}"
elif [ -d "${JENV_ROOT}/versions/${JENV_VERSION}" ]; then
 JENV_NUMBER="${NUMBER}"
elif [ -d "$(/usr/libexec/java_home -v ${NUMBER})" ]; then
 JENV_NUMBER="${NUMBER}"
elif [ -d "${JENV_ROOT}/versions/${NUMBER}" ]; then
 JENV_NUMBER="${NUMBER}"
fi

echo "$JENV_NUMBER"
