#!/usr/bin/env bash
# Summary: Show the current Java provider

set -e
[ -n "$JENV_DEBUG" ] && set -x


JENV_VERSION="$(jenv-version-name)"
JENV_PROVIDER=""

IFS=- read PROVIDER NUMBER <<< "JENV_VERSION"
if [ -d "${JENV_ROOT}/versions/${VERSION}" ]; then
 JENV_PROVIDER=""
elif [ -d "${JENV_ROOT}/versions/${NUMBER}" ]; then
 JENV_PROVIDER=""
elif [ -d "${JENV_ROOT}/versions/${PROVIDER}-${NUMBER}" ]; then
 JENV_PROVIDER="${PROVIDER}"
elif [ -d "$(/usr/libexec/java_home -v ${NUMBER})" ]; then
 JENV_PROVIDER="${PROVIDER}"
fi

echo "$JENV_PROVIDER"
